language: python

python:
  - "3.6"




install:
  - pip install -r requirements.txt
  - pip install coveralls



script:
  - py.test --cov=BucketListAPI BucketListAPI/tests/*

after_success:
  coveralls
